grafana:
  enabled: true
  adminPassword: prom-operator
  service:
    type: LoadBalancer
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 400Mi

alertmanager:
  enabled: true

prometheusOperator:
  enabled: true
