apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-daily-scan
  namespace: default
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trivy
              image: aquasec/trivy:latest
              args:
                - image
                - koganti-infra/service-a:latest
          restartPolicy: OnFailure
