apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/koganti-infra/eks-secure-observable-platform.git
    targetRevision: HEAD
    path: microservices
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
